kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuber-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-react
  template:
    metadata:
      labels:
        app: kuber-react
    spec:
      containers:
        - name: kuber-react
          image: localhost:5000/kuber-react
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuber-gql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-gql
  template:
    metadata:
      labels:
        app: kuber-gql
    spec:
      containers:
        - name: kuber-gql
          image: localhost:5000/kuber-gql
          env:
            - name: aws_access_key_id
              valueFrom:
                # Note - Config maps are not secure as they are visible to anyone who has access to the cluster
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign
                  name: gql-configmap
                  # Specify the key associated with the value
                  key: AWS_ACCESS_KEY_ID
            - name: aws_secret_access_key
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign
                  name: gql-configmap
                  # Specify the key associated with the value
                  key: AWS_SECRET_ACCESS_KEY
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      restartPolicy: Always
# ---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: kuber-mail
# spec:
#   schedule: "*/1 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: kuber-mail
#               image: localhost:5000/kuber-mail
#           restartPolicy: OnFailure
---
kind: Service
apiVersion: v1
metadata:
  name: kuber-react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: kuber-react
---
kind: Service
apiVersion: v1
metadata:
  name: kuber-gql
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      nodePort: 32000
  selector:
    app: kuber-gql
---
#Map uri to external service.
kind: Service
apiVersion: v1
metadata:
  name: kuberlocal
spec:
  type: ExternalName
  externalName: kuber.local
